/**
 * Generated by scripts/generate-bd-locations.mjs from bangladesh-geo-data 4.0.9
 * (MIT, https://www.npmjs.com/package/bangladesh-geo-data).
 * Do not edit by hand; update the generator or its documented overrides.
 */
export const BD_LOCATION_HIERARCHY = {
  "Bagerhat": [
    {
      "name": "Bagerhat Sadar",
      "areas": [
        "Bagerhat Sadar"
      ]
    },
    {
      "name": "Chitalmari",
      "areas": [
        "Chitalmari"
      ]
    },
    {
      "name": "Fakirhat",
      "areas": [
        "Fakirhat"
      ]
    },
    {
      "name": "Kachua",
      "areas": [
        "Kachua"
      ]
    },
    {
      "name": "Mollahat",
      "areas": [
        "Mollahat"
      ]
    },
    {
      "name": "Mongla",
      "areas": [
        "Mongla"
      ]
    },
    {
      "name": "Morrelganj",
      "areas": [
        "Morrelganj"
      ]
    },
    {
      "name": "Rampal",
      "areas": [
        "Rampal"
      ]
    },
    {
      "name": "Sarankhola",
      "areas": [
        "Sarankhola"
      ]
    }
  ],
  "Bandarban": [
    {
      "name": "Ali Kadam",
      "areas": [
        "Ali Kadam"
      ]
    },
    {
      "name": "Bandarban Sadar",
      "areas": [
        "Bandarban Sadar"
      ]
    },
    {
      "name": "Lama",
      "areas": [
        "Lama"
      ]
    },
    {
      "name": "Naikhongchhari",
      "areas": [
        "Naikhongchhari"
      ]
    },
    {
      "name": "Rowangchhari",
      "areas": [
        "Rowangchhari"
      ]
    },
    {
      "name": "Ruma",
      "areas": [
        "Ruma"
      ]
    },
    {
      "name": "Thanchi",
      "areas": [
        "Thanchi"
      ]
    }
  ],
  "Barguna": [
    {
      "name": "Amtali",
      "areas": [
        "Amtali"
      ]
    },
    {
      "name": "Bamna",
      "areas": [
        "Bamna"
      ]
    },
    {
      "name": "Barguna Sadar",
      "areas": [
        "Barguna Sadar"
      ]
    },
    {
      "name": "Betagi",
      "areas": [
        "Betagi"
      ]
    },
    {
      "name": "Patharghata",
      "areas": [
        "Patharghata"
      ]
    },
    {
      "name": "Taltoli",
      "areas": [
        "Taltoli"
      ]
    }
  ],
  "Barishal": [
    {
      "name": "Agailjhara",
      "areas": [
        "Agailjhara"
      ]
    },
    {
      "name": "Babuganj",
      "areas": [
        "Babuganj"
      ]
    },
    {
      "name": "Bakerganj",
      "areas": [
        "Bakerganj"
      ]
    },
    {
      "name": "Banaripara",
      "areas": [
        "Banaripara"
      ]
    },
    {
      "name": "Barishal City",
      "areas": [
        "Airport",
        "Bandara",
        "Barial",
        "Char Aila Kathi",
        "Kashipur",
        "Kotwali",
        "Rupatali",
        "Sadar"
      ]
    },
    {
      "name": "Barishal Sadar",
      "areas": [
        "Barishal Sadar"
      ]
    },
    {
      "name": "Gournadi",
      "areas": [
        "Gournadi"
      ]
    },
    {
      "name": "Hijla",
      "areas": [
        "Hijla"
      ]
    },
    {
      "name": "Mehendiganj",
      "areas": [
        "Mehendiganj"
      ]
    },
    {
      "name": "Muladi",
      "areas": [
        "Muladi"
      ]
    },
    {
      "name": "Uzirpur",
      "areas": [
        "Uzirpur"
      ]
    }
  ],
  "Bhola": [
    {
      "name": "Bhola Sadar",
      "areas": [
        "Bhola Sadar"
      ]
    },
    {
      "name": "Borhanuddin",
      "areas": [
        "Borhanuddin"
      ]
    },
    {
      "name": "Char Fasson",
      "areas": [
        "Char Fasson"
      ]
    },
    {
      "name": "Daulatkhan",
      "areas": [
        "Daulatkhan"
      ]
    },
    {
      "name": "Lalmohan",
      "areas": [
        "Lalmohan"
      ]
    },
    {
      "name": "Monpura",
      "areas": [
        "Monpura"
      ]
    },
    {
      "name": "Tazumuddin",
      "areas": [
        "Tazumuddin"
      ]
    }
  ],
  "Bogura": [
    {
      "name": "Adamdighi",
      "areas": [
        "Adamdighi"
      ]
    },
    {
      "name": "Bogra Sadar",
      "areas": [
        "Bogra Sadar"
      ]
    },
    {
      "name": "Dhunat",
      "areas": [
        "Dhunat"
      ]
    },
    {
      "name": "Dupchanchia",
      "areas": [
        "Dupchanchia"
      ]
    },
    {
      "name": "Gabtali",
      "areas": [
        "Gabtali"
      ]
    },
    {
      "name": "Kahaloo",
      "areas": [
        "Kahaloo"
      ]
    },
    {
      "name": "Nandigram",
      "areas": [
        "Nandigram"
      ]
    },
    {
      "name": "Sariakandi",
      "areas": [
        "Sariakandi"
      ]
    },
    {
      "name": "Shajahanpur",
      "areas": [
        "Shajahanpur"
      ]
    },
    {
      "name": "Sherpur",
      "areas": [
        "Sherpur"
      ]
    },
    {
      "name": "Shibganj",
      "areas": [
        "Shibganj"
      ]
    },
    {
      "name": "Sonatala",
      "areas": [
        "Sonatala"
      ]
    }
  ],
  "Brahmanbaria": [
    {
      "name": "Akhaura",
      "areas": [
        "Akhaura"
      ]
    },
    {
      "name": "Ashuganj",
      "areas": [
        "Ashuganj",
        "Raipur"
      ]
    },
    {
      "name": "Bancharampur",
      "areas": [
        "Bancharampur"
      ]
    },
    {
      "name": "Bijoynagar",
      "areas": [
        "Bijoynagar"
      ]
    },
    {
      "name": "Brahmanbaria Sadar",
      "areas": [
        "Brahmanbaria Sadar"
      ]
    },
    {
      "name": "Kasba",
      "areas": [
        "Kasba"
      ]
    },
    {
      "name": "Nabinagar",
      "areas": [
        "Nabinagar"
      ]
    },
    {
      "name": "Nasirnagar",
      "areas": [
        "Nasirnagar"
      ]
    },
    {
      "name": "Sarail",
      "areas": [
        "Sarail"
      ]
    }
  ],
  "Chandpur": [
    {
      "name": "Chandpur Sadar",
      "areas": [
        "Chandpur Sadar",
        "Hathazari"
      ]
    },
    {
      "name": "Faridganj",
      "areas": [
        "Boalkhali",
        "Faridganj"
      ]
    },
    {
      "name": "Haimchar",
      "areas": [
        "Haimchar"
      ]
    },
    {
      "name": "Hajiganj",
      "areas": [
        "Anwara",
        "Hajiganj"
      ]
    },
    {
      "name": "Kachua",
      "areas": [
        "Kachua"
      ]
    },
    {
      "name": "Matlab Dakkhin",
      "areas": [
        "Banshkhali",
        "Matlab Dakkhin"
      ]
    },
    {
      "name": "Matlab Uttar",
      "areas": [
        "Matlab Uttar",
        "Sandwip"
      ]
    },
    {
      "name": "Shahrasti",
      "areas": [
        "Shahrasti"
      ]
    }
  ],
  "Chapainawabganj": [
    {
      "name": "Bholahat",
      "areas": [
        "Bholahat"
      ]
    },
    {
      "name": "Chapai Nawabganj Sadar",
      "areas": [
        "Chapai Nawabganj Sadar"
      ]
    },
    {
      "name": "Gomastapur",
      "areas": [
        "Gomastapur"
      ]
    },
    {
      "name": "Nachol",
      "areas": [
        "Nachol"
      ]
    },
    {
      "name": "Shibganj",
      "areas": [
        "Shibganj"
      ]
    }
  ],
  "Chattogram": [
    {
      "name": "Anwara",
      "areas": [
        "Anwara"
      ]
    },
    {
      "name": "Banshkhali",
      "areas": [
        "Banshkhali"
      ]
    },
    {
      "name": "Boalkhali",
      "areas": [
        "Boalkhali"
      ]
    },
    {
      "name": "Chandanaish",
      "areas": [
        "Chandanaish"
      ]
    },
    {
      "name": "Chattogram City",
      "areas": [
        "Akbarshah",
        "Bakalia",
        "Bandar",
        "Bayazid",
        "Chandgaon",
        "Chawkbazar",
        "Double Mooring",
        "EPZ",
        "Halishahar",
        "Karnaphuli",
        "Khulshi",
        "Kotwali",
        "Pahartali",
        "Panchlaish",
        "Patenga",
        "Sadarghat"
      ]
    },
    {
      "name": "Fatikchhari",
      "areas": [
        "Fatikchhari"
      ]
    },
    {
      "name": "Hathazari",
      "areas": [
        "Hathazari"
      ]
    },
    {
      "name": "Karnaphuli",
      "areas": [
        "Karnaphuli"
      ]
    },
    {
      "name": "Lohagara",
      "areas": [
        "Lohagara"
      ]
    },
    {
      "name": "Mirsarai",
      "areas": [
        "Mirsarai",
        "Raozan"
      ]
    },
    {
      "name": "Patiya",
      "areas": [
        "Patiya",
        "Sitakund"
      ]
    },
    {
      "name": "Rangunia",
      "areas": [
        "Patiya",
        "Rangunia"
      ]
    },
    {
      "name": "Rauzan",
      "areas": [
        "Rauzan"
      ]
    },
    {
      "name": "Sandwip",
      "areas": [
        "Sandwip",
        "Satkania"
      ]
    },
    {
      "name": "Satkania",
      "areas": [
        "Satkania"
      ]
    },
    {
      "name": "Sitakunda",
      "areas": [
        "Rangunia",
        "Sitakunda"
      ]
    }
  ],
  "Chuadanga": [
    {
      "name": "Alamdanga",
      "areas": [
        "Alamdanga"
      ]
    },
    {
      "name": "Chuadanga Sadar",
      "areas": [
        "Chuadanga Sadar"
      ]
    },
    {
      "name": "Damurhuda",
      "areas": [
        "Damurhuda"
      ]
    },
    {
      "name": "Jibannagar",
      "areas": [
        "Jibannagar"
      ]
    }
  ],
  "Cox's Bazar": [
    {
      "name": "Chakaria",
      "areas": [
        "Chakaria"
      ]
    },
    {
      "name": "Cox's Bazar Sadar",
      "areas": [
        "Cox's Bazar Sadar"
      ]
    },
    {
      "name": "Eidgaon",
      "areas": [
        "Eidgaon"
      ]
    },
    {
      "name": "Kutubdia",
      "areas": [
        "Kutubdia"
      ]
    },
    {
      "name": "Maheshkhali",
      "areas": [
        "Maheshkhali"
      ]
    },
    {
      "name": "Pekua",
      "areas": [
        "Pekua"
      ]
    },
    {
      "name": "Ramu",
      "areas": [
        "Ramu"
      ]
    },
    {
      "name": "Teknaf",
      "areas": [
        "Teknaf"
      ]
    },
    {
      "name": "Ukhiya",
      "areas": [
        "Ukhiya"
      ]
    }
  ],
  "Cumilla": [
    {
      "name": "Barura",
      "areas": [
        "Barura"
      ]
    },
    {
      "name": "Brahmanpara",
      "areas": [
        "Brahmanpara"
      ]
    },
    {
      "name": "Burichong",
      "areas": [
        "Burichong"
      ]
    },
    {
      "name": "Chandina",
      "areas": [
        "Chandina"
      ]
    },
    {
      "name": "Chowddagram",
      "areas": [
        "Chowddagram"
      ]
    },
    {
      "name": "Cumilla City",
      "areas": [
        "Cumilla Sadar",
        "Sadar Dakshin"
      ]
    },
    {
      "name": "Cumilla Sadar",
      "areas": [
        "Cumilla Sadar",
        "Shahrasti"
      ]
    },
    {
      "name": "Daudkandi",
      "areas": [
        "Comilla Sadar South",
        "Daudkandi"
      ]
    },
    {
      "name": "Debidwar",
      "areas": [
        "Bangrabazar",
        "Debidwar"
      ]
    },
    {
      "name": "Homna",
      "areas": [
        "Homna"
      ]
    },
    {
      "name": "Laksam",
      "areas": [
        "Laksam"
      ]
    },
    {
      "name": "Lalmai",
      "areas": [
        "Lalmai"
      ]
    },
    {
      "name": "Meghna",
      "areas": [
        "Meghna"
      ]
    },
    {
      "name": "Monohorgonj",
      "areas": [
        "Monohorgonj"
      ]
    },
    {
      "name": "Muradnagar",
      "areas": [
        "Muradnagar"
      ]
    },
    {
      "name": "Nangalkot",
      "areas": [
        "Nangalkot"
      ]
    },
    {
      "name": "Sadar Dakshin",
      "areas": [
        "Sadar Dakshin"
      ]
    },
    {
      "name": "Titas",
      "areas": [
        "Titas"
      ]
    }
  ],
  "Dhaka": [
    {
      "name": "Dhaka City",
      "areas": [
        "Adabor",
        "Airport",
        "Badda",
        "Banani",
        "Bangshal",
        "Bhashantek",
        "Cantonment",
        "Chawkbazar",
        "Dakshin Khan",
        "Darus-Salam",
        "Demra",
        "Dhanmondi",
        "Gandaria",
        "Gulshan",
        "Hatirjheel",
        "Hazaribagh",
        "Jatrabari",
        "Kadamtoli",
        "Kafrul",
        "Kalabagan",
        "Kamrangirchar",
        "Khilgaon",
        "Khilkhet",
        "Kotwali",
        "Lalbagh",
        "Mirpur Model",
        "Mohammadpur",
        "Motijheel",
        "Mugda",
        "New Market",
        "Pallabi",
        "Paltan Model",
        "Ramna Model",
        "Rampura",
        "Rupnagar",
        "Sabujbagh",
        "Shah Ali",
        "Shahbagh",
        "Shahjahanpur",
        "Sher-e-Bangla Nagar",
        "Shyampur",
        "Sutrapur",
        "Tejgaon",
        "Tejgaon Industrial",
        "Turag",
        "Uttar Khan",
        "Uttara East",
        "Uttara West",
        "Vatara",
        "Wari"
      ]
    },
    {
      "name": "Dhamrai",
      "areas": [
        "Dhamrai"
      ]
    },
    {
      "name": "Dohar",
      "areas": [
        "Dohar"
      ]
    },
    {
      "name": "Keraniganj",
      "areas": [
        "Keraniganj",
        "Keraniganj Model"
      ]
    },
    {
      "name": "Nawabganj",
      "areas": [
        "Nawabganj"
      ]
    },
    {
      "name": "Savar",
      "areas": [
        "Ashulia",
        "Savar"
      ]
    }
  ],
  "Dinajpur": [
    {
      "name": "Birampur",
      "areas": [
        "Birampur"
      ]
    },
    {
      "name": "Birganj",
      "areas": [
        "Birganj"
      ]
    },
    {
      "name": "Birol",
      "areas": [
        "Birol"
      ]
    },
    {
      "name": "Bochaganj",
      "areas": [
        "Bochaganj"
      ]
    },
    {
      "name": "Chirirbandar",
      "areas": [
        "Chirirbandar"
      ]
    },
    {
      "name": "Dinajpur Sadar",
      "areas": [
        "Dinajpur Sadar"
      ]
    },
    {
      "name": "Ghoraghat",
      "areas": [
        "Ghoraghat"
      ]
    },
    {
      "name": "Hakimpur",
      "areas": [
        "Hakimpur"
      ]
    },
    {
      "name": "Kaharol",
      "areas": [
        "Kaharol"
      ]
    },
    {
      "name": "Khansama",
      "areas": [
        "Khansama"
      ]
    },
    {
      "name": "Nawabganj",
      "areas": [
        "Nawabganj"
      ]
    },
    {
      "name": "Parbatipur",
      "areas": [
        "Parbatipur"
      ]
    },
    {
      "name": "Phulbari",
      "areas": [
        "Phulbari"
      ]
    }
  ],
  "Faridpur": [
    {
      "name": "Alfadanga",
      "areas": [
        "Alfadanga"
      ]
    },
    {
      "name": "Bhanga",
      "areas": [
        "Bhanga"
      ]
    },
    {
      "name": "Boalmari",
      "areas": [
        "Boalmari"
      ]
    },
    {
      "name": "Charbhadrasan",
      "areas": [
        "Charbhadrasan"
      ]
    },
    {
      "name": "Faridpur Sadar",
      "areas": [
        "Faridpur Sadar"
      ]
    },
    {
      "name": "Madhukhali",
      "areas": [
        "Madhukhali"
      ]
    },
    {
      "name": "Nagarkanda",
      "areas": [
        "Nagarkanda"
      ]
    },
    {
      "name": "Sadarpur",
      "areas": [
        "Sadarpur"
      ]
    },
    {
      "name": "Saltha",
      "areas": [
        "Saltha"
      ]
    }
  ],
  "Feni": [
    {
      "name": "Chhagalnaiya",
      "areas": [
        "Chhagalnaiya"
      ]
    },
    {
      "name": "Daganbhuiyan",
      "areas": [
        "Daganbhuiyan",
        "Sonagazi"
      ]
    },
    {
      "name": "Feni Sadar",
      "areas": [
        "Feni Sadar",
        "Subarnachar"
      ]
    },
    {
      "name": "Parshuram",
      "areas": [
        "Parshuram"
      ]
    },
    {
      "name": "Phulgazi",
      "areas": [
        "Phulgazi"
      ]
    },
    {
      "name": "Sonagazi",
      "areas": [
        "Sonagazi"
      ]
    }
  ],
  "Gaibandha": [
    {
      "name": "Gaibandha Sadar",
      "areas": [
        "Gaibandha Sadar"
      ]
    },
    {
      "name": "Gobindaganj",
      "areas": [
        "Gobindaganj"
      ]
    },
    {
      "name": "Phulchhari",
      "areas": [
        "Phulchhari"
      ]
    },
    {
      "name": "Polashbari",
      "areas": [
        "Polashbari"
      ]
    },
    {
      "name": "Sadullapur",
      "areas": [
        "Sadullapur"
      ]
    },
    {
      "name": "Saghata",
      "areas": [
        "Saghata"
      ]
    },
    {
      "name": "Sundarganj",
      "areas": [
        "Sundarganj"
      ]
    }
  ],
  "Gazipur": [
    {
      "name": "Gazipur City",
      "areas": [
        "Bason",
        "Gacha",
        "Joydebpur",
        "Kashimpur",
        "Konabari",
        "Pubail",
        "Tongi East",
        "Tongi West"
      ]
    },
    {
      "name": "Gazipur Sadar",
      "areas": [
        "Gazipur Sadar"
      ]
    },
    {
      "name": "Kaliakair",
      "areas": [
        "Kaliakair"
      ]
    },
    {
      "name": "Kaliganj",
      "areas": [
        "Kaliganj"
      ]
    },
    {
      "name": "Kapasia",
      "areas": [
        "Kapasia"
      ]
    },
    {
      "name": "Sreepur",
      "areas": [
        "Sreepur"
      ]
    }
  ],
  "Gopalganj": [
    {
      "name": "Gopalganj Sadar",
      "areas": [
        "Gopalganj Sadar",
        "Kaliganj"
      ]
    },
    {
      "name": "Kashiani",
      "areas": [
        "Kaliakair",
        "Kashiani"
      ]
    },
    {
      "name": "Kotalipara",
      "areas": [
        "Kotalipara"
      ]
    },
    {
      "name": "Muksudpur",
      "areas": [
        "Kapasia",
        "Muksudpur"
      ]
    },
    {
      "name": "Tungipara",
      "areas": [
        "Sreepur",
        "Tungipara"
      ]
    }
  ],
  "Habiganj": [
    {
      "name": "Azmiriganj",
      "areas": [
        "Azmiriganj"
      ]
    },
    {
      "name": "Bahubal",
      "areas": [
        "Bahubal"
      ]
    },
    {
      "name": "Baniachang",
      "areas": [
        "Baniachang"
      ]
    },
    {
      "name": "Chunarughat",
      "areas": [
        "Chunarughat"
      ]
    },
    {
      "name": "Habiganj Sadar",
      "areas": [
        "Habiganj Sadar"
      ]
    },
    {
      "name": "Lakhai",
      "areas": [
        "Lakhai"
      ]
    },
    {
      "name": "Madhabpur",
      "areas": [
        "Madhabpur"
      ]
    },
    {
      "name": "Nabiganj",
      "areas": [
        "Nabiganj"
      ]
    },
    {
      "name": "Shaistaganj",
      "areas": [
        "Shaistaganj"
      ]
    }
  ],
  "Jamalpur": [
    {
      "name": "Bakshiganj",
      "areas": [
        "Bakshiganj"
      ]
    },
    {
      "name": "Dewanganj",
      "areas": [
        "Dewanganj"
      ]
    },
    {
      "name": "Islampur",
      "areas": [
        "Islampur"
      ]
    },
    {
      "name": "Jamalpur Sadar",
      "areas": [
        "Jamalpur Sadar"
      ]
    },
    {
      "name": "Madariganj",
      "areas": [
        "Madariganj"
      ]
    },
    {
      "name": "Melandaha",
      "areas": [
        "Melandaha"
      ]
    },
    {
      "name": "Sarisabari",
      "areas": [
        "Sarisabari"
      ]
    }
  ],
  "Jashore": [
    {
      "name": "Abhaynagar",
      "areas": [
        "Abhaynagar"
      ]
    },
    {
      "name": "Bagharpara",
      "areas": [
        "Bagharpara"
      ]
    },
    {
      "name": "Chowgacha",
      "areas": [
        "Chowgacha"
      ]
    },
    {
      "name": "Jessore Sadar",
      "areas": [
        "Jessore Sadar"
      ]
    },
    {
      "name": "Jhikargacha",
      "areas": [
        "Jhikargacha"
      ]
    },
    {
      "name": "Keshabpur",
      "areas": [
        "Keshabpur"
      ]
    },
    {
      "name": "Monirampur",
      "areas": [
        "Monirampur"
      ]
    },
    {
      "name": "Sharsha",
      "areas": [
        "Sharsha"
      ]
    }
  ],
  "Jhalokati": [
    {
      "name": "Jhalokathi Sadar",
      "areas": [
        "Jhalokathi Sadar"
      ]
    },
    {
      "name": "Kathalia",
      "areas": [
        "Kathalia"
      ]
    },
    {
      "name": "Nalchity",
      "areas": [
        "Nalchity"
      ]
    },
    {
      "name": "Rajapur",
      "areas": [
        "Rajapur"
      ]
    }
  ],
  "Jhenaidah": [
    {
      "name": "Harinakundu",
      "areas": [
        "Harinakundu"
      ]
    },
    {
      "name": "Jhenaidah Sadar",
      "areas": [
        "Jhenaidah Sadar"
      ]
    },
    {
      "name": "Kaliganj",
      "areas": [
        "Kaliganj"
      ]
    },
    {
      "name": "Kotchandpur",
      "areas": [
        "Kotchandpur"
      ]
    },
    {
      "name": "Moheshpur",
      "areas": [
        "Moheshpur"
      ]
    },
    {
      "name": "Shailkupa",
      "areas": [
        "Shailkupa"
      ]
    }
  ],
  "Joypurhat": [
    {
      "name": "Akkelpur",
      "areas": [
        "Akkelpur"
      ]
    },
    {
      "name": "Joypurhat Sadar",
      "areas": [
        "Joypurhat Sadar"
      ]
    },
    {
      "name": "Kalai",
      "areas": [
        "Kalai"
      ]
    },
    {
      "name": "Khetlal",
      "areas": [
        "Khetlal"
      ]
    },
    {
      "name": "Panchbibi",
      "areas": [
        "Panchbibi"
      ]
    }
  ],
  "Khagrachhari": [
    {
      "name": "Dighinala",
      "areas": [
        "Dighinala"
      ]
    },
    {
      "name": "Guimara",
      "areas": [
        "Guimara"
      ]
    },
    {
      "name": "Khagrachhari Sadar",
      "areas": [
        "Khagrachhari Sadar"
      ]
    },
    {
      "name": "Lakshichhari",
      "areas": [
        "Lakshichhari"
      ]
    },
    {
      "name": "Mahalchhari",
      "areas": [
        "Mahalchhari"
      ]
    },
    {
      "name": "Manikchhari",
      "areas": [
        "Manikchhari"
      ]
    },
    {
      "name": "Matiranga",
      "areas": [
        "Matiranga"
      ]
    },
    {
      "name": "Panchhari",
      "areas": [
        "Panchhari"
      ]
    },
    {
      "name": "Ramgarh",
      "areas": [
        "Ramgarh"
      ]
    }
  ],
  "Khulna": [
    {
      "name": "Batiaghata",
      "areas": [
        "Batiaghata"
      ]
    },
    {
      "name": "Dacope",
      "areas": [
        "Dacope"
      ]
    },
    {
      "name": "Dighalia",
      "areas": [
        "Dighalia"
      ]
    },
    {
      "name": "Dumuria",
      "areas": [
        "Dumuria"
      ]
    },
    {
      "name": "Khulna City",
      "areas": [
        "Aranghata",
        "Daulatpur",
        "Horintana",
        "Khalishpur",
        "Khan Jahan Ali",
        "Kotwali",
        "Labanchara",
        "Sonadanga"
      ]
    },
    {
      "name": "Koyra",
      "areas": [
        "Koyra"
      ]
    },
    {
      "name": "Paikgachha",
      "areas": [
        "Paikgachha"
      ]
    },
    {
      "name": "Phultala",
      "areas": [
        "Phultala"
      ]
    },
    {
      "name": "Rupsa",
      "areas": [
        "Rupsa"
      ]
    },
    {
      "name": "Terokhada",
      "areas": [
        "Terokhada"
      ]
    }
  ],
  "Kishoreganj": [
    {
      "name": "Astagram",
      "areas": [
        "Astagram"
      ]
    },
    {
      "name": "Bajitpur",
      "areas": [
        "Bajitpur"
      ]
    },
    {
      "name": "Hossainpur",
      "areas": [
        "Hossainpur"
      ]
    },
    {
      "name": "Itna",
      "areas": [
        "Itna"
      ]
    },
    {
      "name": "Karimganj",
      "areas": [
        "Karimganj"
      ]
    },
    {
      "name": "Katiadi",
      "areas": [
        "Katiadi"
      ]
    },
    {
      "name": "Kishoreganj Sadar",
      "areas": [
        "Kishoreganj Sadar"
      ]
    },
    {
      "name": "Kuliarchar",
      "areas": [
        "Kuliarchar"
      ]
    },
    {
      "name": "Mithamain",
      "areas": [
        "Mithamain"
      ]
    },
    {
      "name": "Nikli",
      "areas": [
        "Nikli"
      ]
    },
    {
      "name": "Pakundia",
      "areas": [
        "Pakundia"
      ]
    },
    {
      "name": "Tarail",
      "areas": [
        "Tarail"
      ]
    },
    {
      "name": "Vairab",
      "areas": [
        "Vairab"
      ]
    }
  ],
  "Kurigram": [
    {
      "name": "Bhurungamari",
      "areas": [
        "Bhurungamari"
      ]
    },
    {
      "name": "Char Rajibpur",
      "areas": [
        "Char Rajibpur"
      ]
    },
    {
      "name": "Chilmari",
      "areas": [
        "Chilmari"
      ]
    },
    {
      "name": "Kurigram Sadar",
      "areas": [
        "Kurigram Sadar"
      ]
    },
    {
      "name": "Nageswari",
      "areas": [
        "Nageswari"
      ]
    },
    {
      "name": "Phulbari",
      "areas": [
        "Phulbari"
      ]
    },
    {
      "name": "Rajarhat",
      "areas": [
        "Rajarhat"
      ]
    },
    {
      "name": "Roumari",
      "areas": [
        "Roumari"
      ]
    },
    {
      "name": "Ulipur",
      "areas": [
        "Ulipur"
      ]
    }
  ],
  "Kushtia": [
    {
      "name": "Bheramara",
      "areas": [
        "Bheramara"
      ]
    },
    {
      "name": "Daulatpur",
      "areas": [
        "Daulatpur"
      ]
    },
    {
      "name": "Khoksa",
      "areas": [
        "Khoksa"
      ]
    },
    {
      "name": "Kumarkhali",
      "areas": [
        "Kumarkhali"
      ]
    },
    {
      "name": "Kushtia Sadar",
      "areas": [
        "Kushtia Sadar"
      ]
    },
    {
      "name": "Mirpur",
      "areas": [
        "Mirpur"
      ]
    }
  ],
  "Lakshmipur": [
    {
      "name": "Kamalnagar",
      "areas": [
        "Fatikchhari",
        "Kamalnagar"
      ]
    },
    {
      "name": "Lakshmipur Sadar",
      "areas": [
        "Chandanaish",
        "Lakshmipur Sadar"
      ]
    },
    {
      "name": "Raipur",
      "areas": [
        "Raipur"
      ]
    },
    {
      "name": "Ramganj",
      "areas": [
        "Mirsharai",
        "Ramganj"
      ]
    },
    {
      "name": "Ramgati",
      "areas": [
        "Lohagara",
        "Ramgati"
      ]
    }
  ],
  "Lalmonirhat": [
    {
      "name": "Aditmari",
      "areas": [
        "Aditmari"
      ]
    },
    {
      "name": "Hatibandha",
      "areas": [
        "Hatibandha"
      ]
    },
    {
      "name": "Kaliganj",
      "areas": [
        "Kaliganj"
      ]
    },
    {
      "name": "Lalmonirhat Sadar",
      "areas": [
        "Lalmonirhat Sadar"
      ]
    },
    {
      "name": "Patgram",
      "areas": [
        "Patgram"
      ]
    }
  ],
  "Madaripur": [
    {
      "name": "Dasar",
      "areas": [
        "Dasar"
      ]
    },
    {
      "name": "Kalkini",
      "areas": [
        "Kalkini"
      ]
    },
    {
      "name": "Madaripur Sadar",
      "areas": [
        "Madaripur Sadar"
      ]
    },
    {
      "name": "Rajoir",
      "areas": [
        "Rajoir"
      ]
    },
    {
      "name": "Shibchar",
      "areas": [
        "Shibchar"
      ]
    }
  ],
  "Magura": [
    {
      "name": "Magura Sadar",
      "areas": [
        "Magura Sadar"
      ]
    },
    {
      "name": "Mohammadpur",
      "areas": [
        "Mohammadpur"
      ]
    },
    {
      "name": "Shalikha",
      "areas": [
        "Shalikha"
      ]
    },
    {
      "name": "Sreepur",
      "areas": [
        "Sreepur"
      ]
    }
  ],
  "Manikganj": [
    {
      "name": "Daulatpur",
      "areas": [
        "Daulatpur"
      ]
    },
    {
      "name": "Ghior",
      "areas": [
        "Ghior"
      ]
    },
    {
      "name": "Harirampur",
      "areas": [
        "Harirampur"
      ]
    },
    {
      "name": "Manikganj Sadar",
      "areas": [
        "Manikganj Sadar"
      ]
    },
    {
      "name": "Saturia",
      "areas": [
        "Saturia"
      ]
    },
    {
      "name": "Shivalaya",
      "areas": [
        "Shivalaya"
      ]
    },
    {
      "name": "Singair",
      "areas": [
        "Singair"
      ]
    }
  ],
  "Meherpur": [
    {
      "name": "Gangni",
      "areas": [
        "Gangni"
      ]
    },
    {
      "name": "Meherpur Sadar",
      "areas": [
        "Meherpur Sadar"
      ]
    },
    {
      "name": "Mujibnagar",
      "areas": [
        "Mujibnagar"
      ]
    }
  ],
  "Moulvibazar": [
    {
      "name": "Bara Lekha",
      "areas": [
        "Bara Lekha"
      ]
    },
    {
      "name": "Juri",
      "areas": [
        "Juri"
      ]
    },
    {
      "name": "Kamalganj",
      "areas": [
        "Kamalganj"
      ]
    },
    {
      "name": "Kulaura",
      "areas": [
        "Kulaura"
      ]
    },
    {
      "name": "Moulvibazar Sadar",
      "areas": [
        "Moulvibazar Sadar"
      ]
    },
    {
      "name": "Rajnagar",
      "areas": [
        "Rajnagar"
      ]
    },
    {
      "name": "Sreemangal",
      "areas": [
        "Sreemangal"
      ]
    }
  ],
  "Munshiganj": [
    {
      "name": "Gazaria",
      "areas": [
        "Gazaria"
      ]
    },
    {
      "name": "Lohajang",
      "areas": [
        "Araihazar",
        "Lohajang"
      ]
    },
    {
      "name": "Munshiganj Sadar",
      "areas": [
        "Munshiganj Sadar"
      ]
    },
    {
      "name": "Sirajdikhan",
      "areas": [
        "Sirajdikhan"
      ]
    },
    {
      "name": "Sreenagar",
      "areas": [
        "Sreenagar"
      ]
    },
    {
      "name": "Tongibari",
      "areas": [
        "Tongibari"
      ]
    }
  ],
  "Mymensingh": [
    {
      "name": "Bhaluka",
      "areas": [
        "Bhaluka"
      ]
    },
    {
      "name": "Dhoubaura",
      "areas": [
        "Dhoubaura"
      ]
    },
    {
      "name": "Fulbaria",
      "areas": [
        "Fulbaria"
      ]
    },
    {
      "name": "Gafargaon",
      "areas": [
        "Gafargaon"
      ]
    },
    {
      "name": "Gouripur",
      "areas": [
        "Gouripur"
      ]
    },
    {
      "name": "Haluaghat",
      "areas": [
        "Haluaghat"
      ]
    },
    {
      "name": "Ishwarganj",
      "areas": [
        "Ishwarganj"
      ]
    },
    {
      "name": "Muktagachha",
      "areas": [
        "Muktagachha"
      ]
    },
    {
      "name": "Mymensingh City",
      "areas": [
        "Kotwali",
        "Sadar"
      ]
    },
    {
      "name": "Mymensingh Sadar",
      "areas": [
        "Mymensingh Sadar"
      ]
    },
    {
      "name": "Nandail",
      "areas": [
        "Nandail"
      ]
    },
    {
      "name": "Phulpur",
      "areas": [
        "Phulpur"
      ]
    },
    {
      "name": "Tarakanda",
      "areas": [
        "Tarakanda"
      ]
    },
    {
      "name": "Trishal",
      "areas": [
        "Trishal"
      ]
    }
  ],
  "Naogaon": [
    {
      "name": "Atrai",
      "areas": [
        "Atrai"
      ]
    },
    {
      "name": "Badalgachi",
      "areas": [
        "Badalgachi"
      ]
    },
    {
      "name": "Dhamoirhat",
      "areas": [
        "Dhamoirhat"
      ]
    },
    {
      "name": "Manda",
      "areas": [
        "Manda"
      ]
    },
    {
      "name": "Mohadevpur",
      "areas": [
        "Mohadevpur"
      ]
    },
    {
      "name": "Naogaon Sadar",
      "areas": [
        "Naogaon Sadar"
      ]
    },
    {
      "name": "Niamatpur",
      "areas": [
        "Niamatpur"
      ]
    },
    {
      "name": "Patnitala",
      "areas": [
        "Patnitala"
      ]
    },
    {
      "name": "Porsha",
      "areas": [
        "Porsha"
      ]
    },
    {
      "name": "Raninagar",
      "areas": [
        "Raninagar"
      ]
    },
    {
      "name": "Sapahar",
      "areas": [
        "Sapahar"
      ]
    }
  ],
  "Narail": [
    {
      "name": "Kalia",
      "areas": [
        "Kalia"
      ]
    },
    {
      "name": "Lohagara",
      "areas": [
        "Lohagara"
      ]
    },
    {
      "name": "Narail Sadar",
      "areas": [
        "Narail Sadar"
      ]
    }
  ],
  "Narayanganj": [
    {
      "name": "Araihazar",
      "areas": [
        "Araihazar",
        "Sonargaon"
      ]
    },
    {
      "name": "Bandar",
      "areas": [
        "Bandar"
      ]
    },
    {
      "name": "Narayanganj City",
      "areas": [
        "Fatullah",
        "Narayanganj Sadar"
      ]
    },
    {
      "name": "Narayanganj Sadar",
      "areas": [
        "Narayanganj Sadar",
        "Rupganj"
      ]
    },
    {
      "name": "Rupganj",
      "areas": [
        "Rupganj"
      ]
    },
    {
      "name": "Sonargaon",
      "areas": [
        "Sonargaon"
      ]
    }
  ],
  "Narsingdi": [
    {
      "name": "Belabo",
      "areas": [
        "Belabo"
      ]
    },
    {
      "name": "Monohardi",
      "areas": [
        "Monohardi"
      ]
    },
    {
      "name": "Narsingdi Sadar",
      "areas": [
        "Narsingdi Sadar"
      ]
    },
    {
      "name": "Palash",
      "areas": [
        "Palash"
      ]
    },
    {
      "name": "Raipura",
      "areas": [
        "Raipura"
      ]
    },
    {
      "name": "Shibpur",
      "areas": [
        "Shibpur"
      ]
    }
  ],
  "Natore": [
    {
      "name": "Bagatipara",
      "areas": [
        "Bagatipara"
      ]
    },
    {
      "name": "Baraigram",
      "areas": [
        "Baraigram"
      ]
    },
    {
      "name": "Gurudaspur",
      "areas": [
        "Gurudaspur"
      ]
    },
    {
      "name": "Lalpur",
      "areas": [
        "Lalpur"
      ]
    },
    {
      "name": "Naldanga",
      "areas": [
        "Naldanga"
      ]
    },
    {
      "name": "Natore Sadar",
      "areas": [
        "Natore Sadar"
      ]
    },
    {
      "name": "Singra",
      "areas": [
        "Singra"
      ]
    }
  ],
  "Netrokona": [
    {
      "name": "Atpara",
      "areas": [
        "Atpara"
      ]
    },
    {
      "name": "Barhatta",
      "areas": [
        "Barhatta"
      ]
    },
    {
      "name": "Durgapur",
      "areas": [
        "Durgapur"
      ]
    },
    {
      "name": "Kendua",
      "areas": [
        "Kendua"
      ]
    },
    {
      "name": "Khaliajuri",
      "areas": [
        "Khaliajuri"
      ]
    },
    {
      "name": "Khalmakanda",
      "areas": [
        "Khalmakanda"
      ]
    },
    {
      "name": "Madan",
      "areas": [
        "Madan"
      ]
    },
    {
      "name": "Mohanganj",
      "areas": [
        "Mohanganj"
      ]
    },
    {
      "name": "Netrokona Sadar",
      "areas": [
        "Netrokona Sadar"
      ]
    },
    {
      "name": "Purbadhala",
      "areas": [
        "Purbadhala"
      ]
    }
  ],
  "Nilphamari": [
    {
      "name": "Dimla",
      "areas": [
        "Dimla"
      ]
    },
    {
      "name": "Domar",
      "areas": [
        "Domar"
      ]
    },
    {
      "name": "Jaldhaka",
      "areas": [
        "Jaldhaka"
      ]
    },
    {
      "name": "Kishoreganj",
      "areas": [
        "Kishoreganj"
      ]
    },
    {
      "name": "Nilphamari Sadar",
      "areas": [
        "Nilphamari Sadar"
      ]
    },
    {
      "name": "Saidpur",
      "areas": [
        "Saidpur"
      ]
    }
  ],
  "Noakhali": [
    {
      "name": "Begumganj",
      "areas": [
        "Begumganj"
      ]
    },
    {
      "name": "Chatkhil",
      "areas": [
        "Chatkhil"
      ]
    },
    {
      "name": "Companiganj",
      "areas": [
        "Companiganj",
        "Ukhia"
      ]
    },
    {
      "name": "Hatia",
      "areas": [
        "Hatia"
      ]
    },
    {
      "name": "Kabirhat",
      "areas": [
        "Kabirhat"
      ]
    },
    {
      "name": "Noakhali Sadar",
      "areas": [
        "Noakhali Sadar",
        "Teknaf"
      ]
    },
    {
      "name": "Senbagh",
      "areas": [
        "Senbagh"
      ]
    },
    {
      "name": "Sonaimuri",
      "areas": [
        "Sonaimuri"
      ]
    },
    {
      "name": "Subarnachar",
      "areas": [
        "Subarnachar"
      ]
    }
  ],
  "Pabna": [
    {
      "name": "Atgharia",
      "areas": [
        "Atgharia"
      ]
    },
    {
      "name": "Bera",
      "areas": [
        "Bera"
      ]
    },
    {
      "name": "Bhangura",
      "areas": [
        "Bhangura"
      ]
    },
    {
      "name": "Chatmohor",
      "areas": [
        "Chatmohor"
      ]
    },
    {
      "name": "Faridpur",
      "areas": [
        "Faridpur"
      ]
    },
    {
      "name": "Ishwardi",
      "areas": [
        "Ishwardi"
      ]
    },
    {
      "name": "Pabna Sadar",
      "areas": [
        "Pabna Sadar"
      ]
    },
    {
      "name": "Santhia",
      "areas": [
        "Santhia"
      ]
    },
    {
      "name": "Sujanagar",
      "areas": [
        "Sujanagar"
      ]
    }
  ],
  "Panchagarh": [
    {
      "name": "Atwari",
      "areas": [
        "Atwari"
      ]
    },
    {
      "name": "Boda",
      "areas": [
        "Boda"
      ]
    },
    {
      "name": "Debiganj",
      "areas": [
        "Debiganj"
      ]
    },
    {
      "name": "Panchagarh Sadar",
      "areas": [
        "Panchagarh Sadar"
      ]
    },
    {
      "name": "Tetulia",
      "areas": [
        "Tetulia"
      ]
    }
  ],
  "Patuakhali": [
    {
      "name": "Bauphal",
      "areas": [
        "Bauphal"
      ]
    },
    {
      "name": "Dashmina",
      "areas": [
        "Dashmina"
      ]
    },
    {
      "name": "Dumki",
      "areas": [
        "Dumki"
      ]
    },
    {
      "name": "Galachipa",
      "areas": [
        "Galachipa"
      ]
    },
    {
      "name": "Kalapara",
      "areas": [
        "Kalapara"
      ]
    },
    {
      "name": "Mirzaganj",
      "areas": [
        "Mirzaganj"
      ]
    },
    {
      "name": "Patuakhali Sadar",
      "areas": [
        "Patuakhali Sadar"
      ]
    },
    {
      "name": "Rangabali",
      "areas": [
        "Rangabali"
      ]
    }
  ],
  "Pirojpur": [
    {
      "name": "Bhandaria",
      "areas": [
        "Bhandaria"
      ]
    },
    {
      "name": "Indurkani",
      "areas": [
        "Indurkani"
      ]
    },
    {
      "name": "Kaukhali",
      "areas": [
        "Kaukhali"
      ]
    },
    {
      "name": "Mathbaria",
      "areas": [
        "Mathbaria"
      ]
    },
    {
      "name": "Nazirpur",
      "areas": [
        "Nazirpur"
      ]
    },
    {
      "name": "Nesarabad",
      "areas": [
        "Nesarabad"
      ]
    },
    {
      "name": "Pirojpur Sadar",
      "areas": [
        "Pirojpur Sadar"
      ]
    }
  ],
  "Rajbari": [
    {
      "name": "Baliakandi",
      "areas": [
        "Baliakandi"
      ]
    },
    {
      "name": "Goalanda",
      "areas": [
        "Goalanda"
      ]
    },
    {
      "name": "Kalukhali",
      "areas": [
        "Kalukhali"
      ]
    },
    {
      "name": "Pangsha",
      "areas": [
        "Pangsha"
      ]
    },
    {
      "name": "Rajbari Sadar",
      "areas": [
        "Rajbari Sadar"
      ]
    }
  ],
  "Rajshahi": [
    {
      "name": "Bagha",
      "areas": [
        "Bagha"
      ]
    },
    {
      "name": "Bagmara",
      "areas": [
        "Bagmara"
      ]
    },
    {
      "name": "Charghat",
      "areas": [
        "Charghat"
      ]
    },
    {
      "name": "Durgapur",
      "areas": [
        "Durgapur"
      ]
    },
    {
      "name": "Godagari",
      "areas": [
        "Godagari"
      ]
    },
    {
      "name": "Mohonpur",
      "areas": [
        "Mohonpur"
      ]
    },
    {
      "name": "Paba",
      "areas": [
        "Paba"
      ]
    },
    {
      "name": "Puthia",
      "areas": [
        "Puthia"
      ]
    },
    {
      "name": "Rajshahi City",
      "areas": [
        "Boalia Model",
        "Motihar",
        "Rajpara",
        "Shah Makhdum"
      ]
    },
    {
      "name": "Tanore",
      "areas": [
        "Tanore"
      ]
    }
  ],
  "Rangamati": [
    {
      "name": "Baghaichhari",
      "areas": [
        "Baghaichhari"
      ]
    },
    {
      "name": "Barkal",
      "areas": [
        "Barkal"
      ]
    },
    {
      "name": "Bilaichhari",
      "areas": [
        "Bilaichhari"
      ]
    },
    {
      "name": "Juraichhari",
      "areas": [
        "Juraichhari"
      ]
    },
    {
      "name": "Kaptai",
      "areas": [
        "Kaptai"
      ]
    },
    {
      "name": "Kaukhali",
      "areas": [
        "Kaukhali"
      ]
    },
    {
      "name": "Langadu",
      "areas": [
        "Langadu"
      ]
    },
    {
      "name": "Naniarchar",
      "areas": [
        "Naniarchar"
      ]
    },
    {
      "name": "Rajasthali",
      "areas": [
        "Rajasthali"
      ]
    },
    {
      "name": "Rangamati Sadar",
      "areas": [
        "Rangamati Sadar"
      ]
    }
  ],
  "Rangpur": [
    {
      "name": "Badarganj",
      "areas": [
        "Badarganj"
      ]
    },
    {
      "name": "Gangachara",
      "areas": [
        "Gangachara"
      ]
    },
    {
      "name": "Kaunia",
      "areas": [
        "Kaunia"
      ]
    },
    {
      "name": "Mithapukur",
      "areas": [
        "Mithapukur"
      ]
    },
    {
      "name": "Pirgacha",
      "areas": [
        "Pirgacha"
      ]
    },
    {
      "name": "Pirganj",
      "areas": [
        "Pirganj"
      ]
    },
    {
      "name": "Rangpur City",
      "areas": [
        "Haragach",
        "Kotwali",
        "Mahiganj",
        "Parshuram",
        "Tajhat",
        "Tukuria"
      ]
    },
    {
      "name": "Rangpur Sadar",
      "areas": [
        "Rangpur Sadar"
      ]
    },
    {
      "name": "Taraganj",
      "areas": [
        "Taraganj"
      ]
    }
  ],
  "Satkhira": [
    {
      "name": "Assasuni",
      "areas": [
        "Assasuni"
      ]
    },
    {
      "name": "Debhata",
      "areas": [
        "Debhata"
      ]
    },
    {
      "name": "Kalaroa",
      "areas": [
        "Kalaroa"
      ]
    },
    {
      "name": "Kaliaganj",
      "areas": [
        "Kaliaganj"
      ]
    },
    {
      "name": "Satkhira Sadar",
      "areas": [
        "Satkhira Sadar"
      ]
    },
    {
      "name": "Shyamnagar",
      "areas": [
        "Shyamnagar"
      ]
    },
    {
      "name": "Tala",
      "areas": [
        "Tala"
      ]
    }
  ],
  "Shariatpur": [
    {
      "name": "Bhedarganj",
      "areas": [
        "Bhedarganj"
      ]
    },
    {
      "name": "Damudya",
      "areas": [
        "Damudya"
      ]
    },
    {
      "name": "Gosairhat",
      "areas": [
        "Gosairhat"
      ]
    },
    {
      "name": "Naria",
      "areas": [
        "Naria"
      ]
    },
    {
      "name": "Shariatpur Sadar",
      "areas": [
        "Shariatpur Sadar"
      ]
    },
    {
      "name": "Zajira",
      "areas": [
        "Zajira"
      ]
    }
  ],
  "Sherpur": [
    {
      "name": "Jhenaigati",
      "areas": [
        "Jhenaigati"
      ]
    },
    {
      "name": "Nakla",
      "areas": [
        "Nakla"
      ]
    },
    {
      "name": "Nalitabari",
      "areas": [
        "Nalitabari"
      ]
    },
    {
      "name": "Sherpur Sadar",
      "areas": [
        "Sherpur Sadar"
      ]
    },
    {
      "name": "Sreebardi",
      "areas": [
        "Sreebardi"
      ]
    }
  ],
  "Sirajganj": [
    {
      "name": "Belkuchi",
      "areas": [
        "Belkuchi"
      ]
    },
    {
      "name": "Chauhali",
      "areas": [
        "Chauhali"
      ]
    },
    {
      "name": "Kamarbandha",
      "areas": [
        "Kamarbandha"
      ]
    },
    {
      "name": "Kazipur",
      "areas": [
        "Kazipur"
      ]
    },
    {
      "name": "Raiganj",
      "areas": [
        "Raiganj"
      ]
    },
    {
      "name": "Shahjadpur",
      "areas": [
        "Shahjadpur"
      ]
    },
    {
      "name": "Sirajganj Sadar",
      "areas": [
        "Sirajganj Sadar"
      ]
    },
    {
      "name": "Tarash",
      "areas": [
        "Tarash"
      ]
    },
    {
      "name": "Ullapara",
      "areas": [
        "Ullapara"
      ]
    }
  ],
  "Sunamganj": [
    {
      "name": "Bishwambharpur",
      "areas": [
        "Bishwambharpur"
      ]
    },
    {
      "name": "Chatak",
      "areas": [
        "Chatak"
      ]
    },
    {
      "name": "Dewarabazar",
      "areas": [
        "Dewarabazar"
      ]
    },
    {
      "name": "Dharmapasha",
      "areas": [
        "Dharmapasha"
      ]
    },
    {
      "name": "Dirai",
      "areas": [
        "Dirai"
      ]
    },
    {
      "name": "Jagannathpur",
      "areas": [
        "Jagannathpur"
      ]
    },
    {
      "name": "Jamalganj",
      "areas": [
        "Jamalganj"
      ]
    },
    {
      "name": "Madhyanagar",
      "areas": [
        "Madhyanagar"
      ]
    },
    {
      "name": "Shalla",
      "areas": [
        "Shalla"
      ]
    },
    {
      "name": "South Sunamganj",
      "areas": [
        "South Sunamganj"
      ]
    },
    {
      "name": "Sunamganj Sadar",
      "areas": [
        "Sunamganj Sadar"
      ]
    },
    {
      "name": "Taherpur",
      "areas": [
        "Taherpur"
      ]
    }
  ],
  "Sylhet": [
    {
      "name": "Balaganj",
      "areas": [
        "Balaganj"
      ]
    },
    {
      "name": "Beanibazar",
      "areas": [
        "Beanibazar"
      ]
    },
    {
      "name": "Bishwanath",
      "areas": [
        "Bishwanath"
      ]
    },
    {
      "name": "Dakshin Surma",
      "areas": [
        "Dakshin Surma"
      ]
    },
    {
      "name": "Fenchuganj",
      "areas": [
        "Fenchuganj"
      ]
    },
    {
      "name": "Golapganj",
      "areas": [
        "Golapganj"
      ]
    },
    {
      "name": "Gowainghat",
      "areas": [
        "Gowainghat"
      ]
    },
    {
      "name": "Jaintapur",
      "areas": [
        "Jaintapur"
      ]
    },
    {
      "name": "Kanaighat",
      "areas": [
        "Kanaighat"
      ]
    },
    {
      "name": "Komponganj",
      "areas": [
        "Komponganj"
      ]
    },
    {
      "name": "Osmani",
      "areas": [
        "Osmani"
      ]
    },
    {
      "name": "Sylhet City",
      "areas": [
        "Airport",
        "Jalalabad",
        "Kotwali",
        "Moglabazar",
        "Shah Paran",
        "South Surma"
      ]
    },
    {
      "name": "Sylhet Sadar",
      "areas": [
        "Sylhet Sadar"
      ]
    },
    {
      "name": "Zakiganj",
      "areas": [
        "Zakiganj"
      ]
    }
  ],
  "Tangail": [
    {
      "name": "Basail",
      "areas": [
        "Basail"
      ]
    },
    {
      "name": "Bhuapur",
      "areas": [
        "Bhuapur"
      ]
    },
    {
      "name": "Delduar",
      "areas": [
        "Delduar"
      ]
    },
    {
      "name": "Dhanbari",
      "areas": [
        "Dhanbari"
      ]
    },
    {
      "name": "Ghatail",
      "areas": [
        "Ghatail"
      ]
    },
    {
      "name": "Gopalpur",
      "areas": [
        "Gopalpur"
      ]
    },
    {
      "name": "Kalihati",
      "areas": [
        "Kalihati"
      ]
    },
    {
      "name": "Madhupur",
      "areas": [
        "Madhupur"
      ]
    },
    {
      "name": "Mirzapur",
      "areas": [
        "Mirzapur"
      ]
    },
    {
      "name": "Nagarpur",
      "areas": [
        "Nagarpur"
      ]
    },
    {
      "name": "Sakhipur",
      "areas": [
        "Sakhipur"
      ]
    },
    {
      "name": "Tangail Sadar",
      "areas": [
        "Tangail Sadar"
      ]
    }
  ],
  "Thakurgaon": [
    {
      "name": "Baliadangi",
      "areas": [
        "Baliadangi"
      ]
    },
    {
      "name": "Haripur",
      "areas": [
        "Haripur"
      ]
    },
    {
      "name": "Pirganj",
      "areas": [
        "Pirganj"
      ]
    },
    {
      "name": "Ranisankail",
      "areas": [
        "Ranisankail"
      ]
    },
    {
      "name": "Thakurgaon Sadar",
      "areas": [
        "Thakurgaon Sadar"
      ]
    }
  ]
} as const
