import { relations, type SQL, sql } from 'drizzle-orm'
import {
  type AnyPgColumn,
  customType,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'

/**
 * Catalog tables. Drizzle definitions only — no Zod here, no server imports
 * beyond Drizzle itself. Validators live in `validators.ts` so client components
 * never drag the ORM into the browser bundle.
 *
 * Rationale for the shape of all this is in docs/02-data-model.md; the decisions
 * worth not re-litigating are: every product has at least one variant, price and
 * stock live on the variant, and money is integer poisha.
 */

/** Postgres 18 ships uuidv7() natively — time-sortable ids without an extension. */
const primaryId = () =>
  uuid('id')
    .primaryKey()
    .default(sql`uuidv7()`)

/** Drizzle has no built-in tsvector, so declare it. */
const tsvector = customType<{ data: string }>({
  dataType: () => 'tsvector',
})

export const categories = pgTable(
  'categories',
  {
    id: primaryId(),
    slug: text('slug').notNull(),
    name: text('name').notNull(),
    description: text('description'),
    // Self-referencing. Depth is capped at two levels in the service layer —
    // deeper trees make navigation and queries disproportionately painful.
    // AnyPgColumn breaks the circular type reference a self-FK would otherwise create.
    parentId: uuid('parent_id').references((): AnyPgColumn => categories.id, {
      onDelete: 'restrict',
    }),
    imageKey: text('image_key'),
    position: integer('position').notNull().default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('categories_slug_idx').on(t.slug),
    index('categories_parent_idx').on(t.parentId, t.position),
  ],
)

export const products = pgTable(
  'products',
  {
    id: primaryId(),
    slug: text('slug').notNull(),
    title: text('title').notNull(),
    description: text('description'),
    categoryId: uuid('category_id').references(() => categories.id, { onDelete: 'restrict' }),
    brand: text('brand'),
    /** 'draft' | 'active' | 'archived' — archived stays queryable for order history. */
    status: text('status').notNull().default('draft'),
    // Generated by Postgres, so it can never drift from the columns it indexes.
    // Title outweighs brand outweighs description when ranking.
    searchVector: tsvector('search_vector').generatedAlwaysAs(
      (): SQL =>
        sql`setweight(to_tsvector('english', coalesce(${products.title}, '')), 'A') || setweight(to_tsvector('english', coalesce(${products.brand}, '')), 'B') || setweight(to_tsvector('english', coalesce(${products.description}, '')), 'C')`,
    ),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('products_slug_idx').on(t.slug),
    index('products_status_category_idx').on(t.status, t.categoryId),
    index('products_search_idx').using('gin', t.searchVector),
  ],
)

export const productImages = pgTable(
  'product_images',
  {
    id: primaryId(),
    productId: uuid('product_id')
      .notNull()
      .references(() => products.id, { onDelete: 'cascade' }),
    /** R2 object key. The public URL is derived at render time, never stored. */
    r2Key: text('r2_key').notNull(),
    alt: text('alt'),
    position: integer('position').notNull().default(0),
    createdAt: timestamp('created_at').notNull().defaultNow(),
  },
  (t) => [index('product_images_product_idx').on(t.productId, t.position)],
)

export const productVariants = pgTable(
  'product_variants',
  {
    id: primaryId(),
    productId: uuid('product_id')
      .notNull()
      .references(() => products.id, { onDelete: 'cascade' }),
    sku: text('sku').notNull(),
    /** Null for single-variant products, which still get a row. */
    title: text('title'),
    /** Integer poisha. Never a float — see docs/02-data-model.md decision 1. */
    price: integer('price').notNull(),
    compareAtPrice: integer('compare_at_price'),
    /**
     * A cached projection of the inventory_movements ledger (P2), maintained
     * transactionally. Decrement conditionally, never read-then-write.
     */
    stock: integer('stock').notNull().default(0),
    weightGrams: integer('weight_grams').notNull().default(0),
    barcode: text('barcode'),
    /** e.g. {"size": "M", "colour": "Red"} */
    options: jsonb('options').$type<Record<string, string>>().notNull().default({}),
    position: integer('position').notNull().default(0),
    /**
     * Archived, never deleted, from P2 onward.
     *
     * order_items and inventory_movements point here. Removing a variant an
     * order was placed against would either break the foreign key or erase the
     * record of what was sold — so an admin removing a size hides it instead.
     */
    archivedAt: timestamp('archived_at'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
  },
  (t) => [
    uniqueIndex('product_variants_sku_idx').on(t.sku),
    index('product_variants_product_idx').on(t.productId, t.position),
  ],
)

/** Relations power `db.query.*.findMany({ with: ... })`. */
export const categoriesRelations = relations(categories, ({ one, many }) => ({
  parent: one(categories, {
    fields: [categories.parentId],
    references: [categories.id],
    relationName: 'category_parent',
  }),
  children: many(categories, { relationName: 'category_parent' }),
  products: many(products),
}))

export const productsRelations = relations(products, ({ one, many }) => ({
  category: one(categories, { fields: [products.categoryId], references: [categories.id] }),
  variants: many(productVariants),
  images: many(productImages),
}))

export const productImagesRelations = relations(productImages, ({ one }) => ({
  product: one(products, { fields: [productImages.productId], references: [products.id] }),
}))

export const productVariantsRelations = relations(productVariants, ({ one }) => ({
  product: one(products, { fields: [productVariants.productId], references: [products.id] }),
}))

export type Category = typeof categories.$inferSelect
export type Product = typeof products.$inferSelect
export type ProductImage = typeof productImages.$inferSelect
export type ProductVariant = typeof productVariants.$inferSelect
export type ProductStatus = 'draft' | 'active' | 'archived'
